name : First GitHub Action

on : [push]

jobs :
  greeting :
    runs-on : ubuntu-latest
    steps :
    - name : Greet the Dev
      run : echo "Hello Dev, this is my first GitHub Action"
  build :
    runs-on : ubuntu-latest
    steps :
    - name : Build NET
      run : echo "Aca ejecutaria el comando para Build un ASP.NET App"
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.0.0
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: '6.0'
    - run: ls
  test :
    runs-on : ubuntu-latest
    steps :
    - name : Test with xUnit
      run : echo "Aca ejecutaria los Unit Test y demas"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy to Server
      run: echo "Aca ejecutaria el comando para Publicar una aplicación"
    
